pub mod bio;
pub mod chat_box;
pub mod comment_section;
pub mod community_guidelines;
pub mod delete_album;
pub mod delete_band;
pub mod delete_lyrics;
pub mod delete_photo;
pub mod delete_photo_album;
pub mod delete_tabs;
pub mod delete_video;
pub mod delete_video_category;
pub mod edit_band;
pub mod edit_album;
pub mod edit_lyrics;
pub mod edit_photo;
pub mod edit_photo_album;
pub mod edit_profile_info;
pub mod edit_profile_password;
pub mod edit_profile_picture;
pub mod edit_tabs;
pub mod edit_video;
pub mod edit_video_category;
pub mod forgot_password;
pub mod home;
pub mod lyrics;
pub mod lyrics_booklet;
pub mod members;
pub mod page_not_found;
pub mod photos;
pub mod privacy_policy;
pub mod sign_in;
pub mod sign_up;
pub mod tabs;
pub mod terms_of_service;
pub mod videos;

pub const PAGE_NAME_HOME: &str = "home";
pub const PAGE_NAME_BIO: &str = "bio";
pub const PAGE_NAME_LYRICS: &str = "lyrics";
pub const PAGE_NAME_TABS: &str = "tabs";
pub const PAGE_NAME_PHOTOS: &str = "photos";
pub const PAGE_NAME_VIDEOS: &str = "videos";
pub const PAGE_NAME_MEMBERS: &str = "members";